---
name: main
on: [push]
jobs:
  plan:
    env:
      ARM_USE_OIDC: true
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
    runs-on: ubuntu-latest
    permissions:
      id-token: write

    steps:
      - uses: actions/checkout@v6
      - uses: hashicorp/setup-terraform@v4

      - run: terraform init
      - name: terraform plan
        run: |
          terraform plan -out=tfplan
      - uses: actions/upload-artifact@v4
        with:
          name: tfplan
          path: tfplan
  apply:
    needs: plan
    env:
      ARM_USE_OIDC: true
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
    environment: deployment
    runs-on: ubuntu-latest
    permissions:
      id-token: write

    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v4

      - uses: actions/download-artifact@v4
        with:
          name: tfplan

      - run: terraform init

      - run: terraform apply tfplan
