---
name: terraform
on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        required: true
        options:
          - test
          - staging
          - prod
      version:
        required: true
        type: string
        default: latest
jobs:
  plan:
    env:
      TF_TOKEN_app_terraform_io: ${{ secrets.HCP_TERRAFORM_TOKEN }}
      TF_VAR_container_image:
        demo/quickstart:${{ inputs.version }}
      TF_CLOUD_ORGANIZATION: medkhabt-org
      TF_WORKSPACE:
        terraform-and-aca-demo-${{ inputs.environment }}
      ARM_USE_OIDC: true
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v6
      - uses: hashicorp/setup-terraform@v4
      - uses: gruntwork-io/terragrunt-action@v3
        with:
          tg_version: "1.1.5"
          tf_path: terraform

      - name: terraform plan
        working-directory: terraform/live/${{ inputs.environment }}
        run: |
          terragrunt plan -out="${GITHUB_WORKSPACE}/tfplan"
      - uses: actions/upload-artifact@v4
        with:
          name: tfplan
          path: tfplan
  confirm:
    needs: plan
    environment: deployment
    runs-on: ubuntu-latest
    steps:
      - run: echo "confirmed"
  apply:
    needs: confirm
    env:
      TF_TOKEN_app_terraform_io: ${{ secrets.HCP_TERRAFORM_TOKEN }}
      TF_VAR_container_image:
        mcr.microsoft.com/k8se/quickstart:${{ inputs.version }}
      TF_CLOUD_ORGANIZATION: medkhabt-org
      TF_WORKSPACE:
        terraform-and-aca-demo-${{ inputs.environment }}
      ARM_USE_OIDC: true
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v4
      - uses: gruntwork-io/terragrunt-action@v3
        with:
          tg_version: "1.1.5"
          tf_path: terraform

      - uses: actions/download-artifact@v4
        with:
          name: tfplan

      - name: Terragrunt Apply
        working-directory: terraform/live/${{ inputs.environment }}
        run: terragrunt apply "${GITHUB_WORKSPACE}/tfplan"
