---
name: terraform-destroy

on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        required: true
        options:
          - test
          - staging
          - prod

      confirmation:
        description: 'Type DESTROY to confirm'
        required: true
        type: string

jobs:
  destroy-plan:
    if: ${{ inputs.confirmation == 'DESTROY' }}

    env:
      TF_TOKEN_app_terraform_io: ${{ secrets.HCP_TERRAFORM_TOKEN }}
      TF_CLOUD_ORGANIZATION: medkhabt-org
      TF_WORKSPACE: terraform-and-aca-demo-${{ inputs.environment }}

      ARM_USE_OIDC: true
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}

      # Include this if your configuration still requires the variable
      TF_VAR_container_image: demo/quickstart:latest

    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v6

      - uses: hashicorp/setup-terraform@v4

      - uses: gruntwork-io/terragrunt-action@v3
        with:
          tg_version: "1.1.5"
          tf_path: terraform

      - name: Terraform Destroy Plan
        working-directory: terraform/live/${{ inputs.environment }}
        run: |
          terragrunt plan \
            -destroy \
            -out="${GITHUB_WORKSPACE}/tfplan-destroy"

      - uses: actions/upload-artifact@v4
        with:
          name: tfplan-destroy
          path: tfplan-destroy

  confirm-destroy:
    needs: destroy-plan

    # Configure approval rules for this GitHub Environment
    environment: destruction

    runs-on: ubuntu-latest

    steps:
      - run: echo "Destroy approved"

  destroy:
    needs: confirm-destroy

    env:
      TF_TOKEN_app_terraform_io: ${{ secrets.HCP_TERRAFORM_TOKEN }}
      TF_CLOUD_ORGANIZATION: medkhabt-org
      TF_WORKSPACE: terraform-and-aca-demo-${{ inputs.environment }}

      ARM_USE_OIDC: true
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}

    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v6

      - uses: hashicorp/setup-terraform@v4

      - uses: gruntwork-io/terragrunt-action@v3
        with:
          tg_version: "1.1.5"
          tf_path: terraform

      - uses: actions/download-artifact@v4
        with:
          name: tfplan-destroy

      - name: Terragrunt Destroy
        working-directory: terraform/live/${{ inputs.environment }}
        run: |
          terragrunt apply "${GITHUB_WORKSPACE}/tfplan-destroy"
